# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f3ea94e905b93b9b8b2d01a9e2fae8573fe52145f8cb18f23a35ede1f7da9959efb1af940c6fc390fe9efaa822bab10cec0067f5379c0f8657c08d7cc9af742

test:
  secret_key_base: 09604fe0892ccb7e851ca687167aaac80f6876f19b974c0281167f62678e04857dbe840c0f9bc8be233d779e98c9c923a1e026797bb8a042265bfafbfba4bf1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
